name: Check File Name Collisions

on:
  pull_request:
    paths:
      - '**/*.m'  # Trigger the workflow when .m files are added or modified

jobs:
  check_collisions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check File Name Collisions
        run: |
            chmod +x ./check_filename_collisions.sh
            bash ./check_filename_collisions.sh
